---
efiBootLoader:     "grub"
kernelSearchPath:  "/boot"
grubInstall:       "grub-install"
grubMkconfig:      "grub-mkconfig"
grubCfg:           "/boot/grub/grub.cfg"
grubProbe:         "grub-probe"
efiBootloaderId:   "HORUS"
installEFIFallback: true
