---
defaultGroups:
    - sudo
    - audio
    - video
    - plugdev
    - netdev
    - bluetooth
    - dialout
    - i2c
autologinGroup:  autologin
doAutologin:     false
sudoersGroup:    sudo
setRootPassword: false
availableShells: /bin/bash
allowWeakPasswords:        false
allowWeakPasswordsDefault: false
userShell: /bin/bash
